import AppKit
import CoreGraphics

/// 剪贴板快照，用于临时写入后恢复。尽力恢复所有类型；不可读的类型会跳过。
struct PasteboardSnapshot {
    let items: [[(NSPasteboard.PasteboardType, Data)]]

    static func capture(from pb: NSPasteboard) -> PasteboardSnapshot {
        var collected: [[(NSPasteboard.PasteboardType, Data)]] = []
        for item in pb.pasteboardItems ?? [] {
            var pairs: [(NSPasteboard.PasteboardType, Data)] = []
            for type in item.types {
                if let data = item.data(forType: type) {
                    pairs.append((type, data))
                }
            }
            collected.append(pairs)
        }
        return PasteboardSnapshot(items: collected)
    }

    func restore(to pb: NSPasteboard) {
        pb.clearContents()
        guard !items.isEmpty else { return }
        let restored: [NSPasteboardItem] = items.map { pairs in
            let item = NSPasteboardItem()
            for (type, data) in pairs {
                item.setData(data, forType: type)
            }
            return item
        }
        pb.writeObjects(restored)
    }
}

/// 向前台 App 发送 ⌘ 组合键。需要辅助功能权限。
enum KeyboardEvents {
    static let keyCodeC: CGKeyCode = 8
    static let keyCodeV: CGKeyCode = 9

    static func postCommand(_ keyCode: CGKeyCode) {
        // privateState：不叠加用户此刻仍按着的 Ctrl/Option（热键刚按下时常见）。
        let source = CGEventSource(stateID: .privateState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
    }

    /// 等用户松开热键的修饰键，避免合成的 ⌘C 被当成 ⌃⌥⌘C。
    static func waitForModifierRelease(timeout: TimeInterval) async {
        let deadline = Date().addingTimeInterval(timeout)
        let held: CGEventFlags = [.maskControl, .maskAlternate, .maskShift]
        while Date() < deadline {
            let flags = CGEventSource.flagsState(.combinedSessionState)
            if flags.intersection(held).isEmpty { return }
            try? await Task.sleep(nanoseconds: 15_000_000)
        }
    }
}

/// 读取剪贴板里的文字，作为没有选区时的原文来源。
enum ClipboardReader {
    /// 超过这个长度多半不是想处理的一段文字（日志、整份文件）。
    static let maximumCharacters = 20_000

    /// 密码管理器等会用这些类型标记敏感或临时内容，不能读去发给模型。
    static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    static func text(from pb: NSPasteboard = .general) -> String? {
        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: concealedTypes),
              let raw = pb.string(forType: .string) else {
            return nil
        }
        let text = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty, text.count <= maximumCharacters else { return nil }
        return text
    }
}

/// 用 ⌘C 复制前台 App 的选中文字，读取后恢复原剪贴板。
/// 不依赖目标 App 的辅助功能实现，Electron/网页也适用。
@MainActor
enum SelectionCopier {
    static func copySelection(timeout: TimeInterval = 0.3) async -> String? {
        guard AccessibilityPermissionManager.shared.isTrusted() else { return nil }
        await KeyboardEvents.waitForModifierRelease(timeout: 0.4)

        let pb = NSPasteboard.general
        let snapshot = PasteboardSnapshot.capture(from: pb)
        let before = pb.changeCount
        KeyboardEvents.postCommand(KeyboardEvents.keyCodeC)

        let deadline = Date().addingTimeInterval(timeout)
        while pb.changeCount == before, Date() < deadline {
            try? await Task.sleep(nanoseconds: 15_000_000)
        }
        guard pb.changeCount != before else {
            Log.flow.notice("capture: ⌘C 未产生内容（没有选区）")
            return nil
        }
        // Finder 等复制的是文件，不是文字。
        let isFileCopy = pb.types?.contains(.fileURL) == true
        let copied = isFileCopy ? nil : pb.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        snapshot.restore(to: pb)
        guard let copied, !copied.isEmpty else { return nil }
        Log.flow.notice("capture: ⌘C 复制到选中文字（\(copied.count) 字）")
        return copied
    }
}
